name: starter_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  intl: ^0.19.0
  logger: ^2.4.0
  provider: ^6.1.2
  dart_jsonwebtoken: ^2.14.0
  shared_preferences: ^2.3.2
  flutter_native_splash: ^2.4.1
  flutter_localizations:
    sdk: flutter
  internet_connection_checker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/

flutter_native_splash:
  color: "#FFF4E7"
  image: assets/images/splash/logo.png

  android_12:
    color: "#FFF4E7"
    image: assets/images/splash/logo-android12-above.png

  # Disable the splash screen on web
  web: false
