name: starterapp
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.6.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  dart_jsonwebtoken: ^2.14.0
  internet_connection_checker: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/images/