name: Public Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk

      - name: Build App Bundle
        run: flutter build appbundle

      - name: Create Release Tag
        id: create_tag
        run: |
          TAG_NAME=v1.${{ github.run_number }}
          echo "TAG_NAME=$TAG_NAME"
          git tag $TAG_NAME
          git push origin $TAG_NAME
          echo "::set-output name=tag_name::$TAG_NAME"

      - name: Upload APK to GitHub Releases
        uses: softprops/action-gh-release@v1
        with:
          files: build/app/outputs/flutter-apk/app-release.apk
          tag_name: ${{ steps.create_tag.outputs.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
